version: "3.8"

services:
  backend:
    image: fadhillahhaidarrahyang/fad-server-image:latest
    restart: always
    environment:
      PORT: ${PORT}
      CONNECTION_URL: ${CONNECTION_URL}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      DEFAULT_CLIENT_URL: ${DEFAULT_CLIENT_URL}
    ports:
      - "3096:3096"

  frontend:
    image: fadhillahhaidarrahyang/fad-client-image:latest
    restart: always
    depends_on:
      - backend
    ports:
      - "3095:3095"